apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  namespace: greeting-ns
spec:
  type: LoadBalancer
  selector:
    app: greeting-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8090